//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.14.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Home</summary>
	[PublishedModel("home")]
	public partial class Home : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		public new const string ModelTypeAlias = "home";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Home(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// About Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("aboutDescription")]
		public virtual global::System.Web.IHtmlString AboutDescription => this.Value<global::System.Web.IHtmlString>("aboutDescription");

		///<summary>
		/// Menu ID
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("aboutMenuId")]
		public virtual string AboutMenuId => this.Value<string>("aboutMenuId");

		///<summary>
		/// Menu Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("aboutMenuName")]
		public virtual string AboutMenuName => this.Value<string>("aboutMenuName");

		///<summary>
		/// About Sub Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("aboutSubTitle")]
		public virtual string AboutSubTitle => this.Value<string>("aboutSubTitle");

		///<summary>
		/// About Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("aboutTitle")]
		public virtual string AboutTitle => this.Value<string>("aboutTitle");

		///<summary>
		/// Color Theme
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("colorTheme")]
		public virtual string ColorTheme => this.Value<string>("colorTheme");

		///<summary>
		/// Contact Address Detail
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("contactAddressDetail")]
		public virtual global::System.Web.IHtmlString ContactAddressDetail => this.Value<global::System.Web.IHtmlString>("contactAddressDetail");

		///<summary>
		/// Contact Address Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("contactAddressTitle")]
		public virtual string ContactAddressTitle => this.Value<string>("contactAddressTitle");

		///<summary>
		/// Contact Email Detail
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("contactEmailDetail")]
		public virtual global::System.Web.IHtmlString ContactEmailDetail => this.Value<global::System.Web.IHtmlString>("contactEmailDetail");

		///<summary>
		/// Contact Email Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("contactEmailHeader")]
		public virtual string ContactEmailHeader => this.Value<string>("contactEmailHeader");

		///<summary>
		/// Contact Excerpt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("contactExcerpt")]
		public virtual string ContactExcerpt => this.Value<string>("contactExcerpt");

		///<summary>
		/// Contact Form Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("contactFormHeader")]
		public virtual string ContactFormHeader => this.Value<string>("contactFormHeader");

		///<summary>
		/// Contact Form Success Message
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("contactFormSuccessMessage")]
		public virtual string ContactFormSuccessMessage => this.Value<string>("contactFormSuccessMessage");

		///<summary>
		/// Contact Form Warning Message
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("contactFormWarningMessage")]
		public virtual string ContactFormWarningMessage => this.Value<string>("contactFormWarningMessage");

		///<summary>
		/// Contact Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("contactHeader")]
		public virtual string ContactHeader => this.Value<string>("contactHeader");

		///<summary>
		/// Menu ID
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("contactMenuId")]
		public virtual string ContactMenuId => this.Value<string>("contactMenuId");

		///<summary>
		/// Menu Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("contactMenuName")]
		public virtual string ContactMenuName => this.Value<string>("contactMenuName");

		///<summary>
		/// Contact Phone Detail
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("contactPhoneDetail")]
		public virtual global::System.Web.IHtmlString ContactPhoneDetail => this.Value<global::System.Web.IHtmlString>("contactPhoneDetail");

		///<summary>
		/// Contact Phone Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("contactPhoneTitle")]
		public virtual string ContactPhoneTitle => this.Value<string>("contactPhoneTitle");

		///<summary>
		/// Contact Sub Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("contactSubHeader")]
		public virtual string ContactSubHeader => this.Value<string>("contactSubHeader");

		///<summary>
		/// Feature Partners
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("featurePartners")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.FeaturePartner> FeaturePartners => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.FeaturePartner>>("featurePartners");

		///<summary>
		/// Feature Services
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("featureServices")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.FeatureService> FeatureServices => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.FeatureService>>("featureServices");

		///<summary>
		/// Feature Stats
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("featureStats")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.FeauterStatsCount> FeatureStats => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.FeauterStatsCount>>("featureStats");

		///<summary>
		/// Font
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("font")]
		public virtual string Font => this.Value<string>("font");

		///<summary>
		/// Address
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("footerAddress")]
		public virtual string FooterAddress => this.Value<string>("footerAddress");

		///<summary>
		/// Call To Action Caption: Caption on the Call To Action Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("footerCTACaption")]
		public virtual string FooterCtacaption => this.Value<string>("footerCTACaption");

		///<summary>
		/// Call To Action Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("FooterCtalink")]
		public virtual global::Umbraco.Core.Models.PublishedContent.IPublishedContent FooterCtalink => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("FooterCtalink");

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("footerDescription")]
		public virtual string FooterDescription => this.Value<string>("footerDescription");

		///<summary>
		/// Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("footerHeader")]
		public virtual string FooterHeader => this.Value<string>("footerHeader");

		///<summary>
		/// Footer Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("footerLogo")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops FooterLogo => this.Value<global::Umbraco.Core.Models.MediaWithCrops>("footerLogo");

		///<summary>
		/// Menu ID
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("footerMenuId")]
		public virtual string FooterMenuId => this.Value<string>("footerMenuId");

		///<summary>
		/// Menu Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("footerMenuName")]
		public virtual string FooterMenuName => this.Value<string>("footerMenuName");

		///<summary>
		/// Footer Sub Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("footerSubHeader")]
		public virtual string FooterSubHeader => this.Value<string>("footerSubHeader");

		///<summary>
		/// Hero Background: Spice up the homepage by adding a beautiful photo that relates to your business
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("HeroBackgroundImage")]
		public virtual global::Umbraco.Core.Models.PublishedContent.IPublishedContent HeroBackgroundImage => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("HeroBackgroundImage");

		///<summary>
		/// Call To Action Caption: The caption on the button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("heroCTACaption")]
		public virtual string HeroCtacaption => this.Value<string>("heroCTACaption");

		///<summary>
		/// Call To Action Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("HeroCtalink")]
		public virtual global::Umbraco.Core.Models.PublishedContent.IPublishedContent HeroCtalink => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("HeroCtalink");

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("heroDescription")]
		public virtual string HeroDescription => this.Value<string>("heroDescription");

		///<summary>
		/// Header: This is the main headline for the hero area on the Homepage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("heroHeader")]
		public virtual string HeroHeader => this.Value<string>("heroHeader");

		///<summary>
		/// Hero Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("heroLogo")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops HeroLogo => this.Value<global::Umbraco.Core.Models.MediaWithCrops>("heroLogo");

		///<summary>
		/// Menu ID
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("homeMenuId")]
		public virtual string HomeMenuId => this.Value<string>("homeMenuId");

		///<summary>
		/// Menu Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("homeMenuName")]
		public virtual string HomeMenuName => this.Value<string>("homeMenuName");

		///<summary>
		/// Partner Excerpt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("partnerExcerpt")]
		public virtual string PartnerExcerpt => this.Value<string>("partnerExcerpt");

		///<summary>
		/// Partner Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("partnerHeader")]
		public virtual string PartnerHeader => this.Value<string>("partnerHeader");

		///<summary>
		/// Menu ID
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("partnerMenuId")]
		public virtual string PartnerMenuId => this.Value<string>("partnerMenuId");

		///<summary>
		/// Menu Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("partnerMenuName")]
		public virtual string PartnerMenuName => this.Value<string>("partnerMenuName");

		///<summary>
		/// Partner Sub Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("partnerSubHeader")]
		public virtual string PartnerSubHeader => this.Value<string>("partnerSubHeader");

		///<summary>
		/// Service Cover Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("serviceCoverImage")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops ServiceCoverImage => this.Value<global::Umbraco.Core.Models.MediaWithCrops>("serviceCoverImage");

		///<summary>
		/// Service Excerpt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("serviceExcerpt")]
		public virtual string ServiceExcerpt => this.Value<string>("serviceExcerpt");

		///<summary>
		/// Service Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("serviceHeader")]
		public virtual string ServiceHeader => this.Value<string>("serviceHeader");

		///<summary>
		/// Menu ID
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("serviceMenuId")]
		public virtual string ServiceMenuId => this.Value<string>("serviceMenuId");

		///<summary>
		/// Menu Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("serviceMenuName")]
		public virtual string ServiceMenuName => this.Value<string>("serviceMenuName");

		///<summary>
		/// Service Sub Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("serviceSubHeader")]
		public virtual string ServiceSubHeader => this.Value<string>("serviceSubHeader");

		///<summary>
		/// Logo: Optional. If you add a logo it'll be used in the upper left corner instead of the site name. Make sure to use a transparent logo for best results
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("SiteLogo")]
		public virtual global::Umbraco.Core.Models.PublishedContent.IPublishedContent SiteLogo => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("SiteLogo");

		///<summary>
		/// Sitename: Used on the homepage as well as the title and social cards
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("sitename")]
		public virtual string Sitename => this.Value<string>("sitename");

		///<summary>
		/// Socials
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("socials")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.SocialIcon> Socials => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.SocialIcon>>("socials");

		///<summary>
		/// Work Gallery
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("workGallery")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.GalleryElement> WorkGallery => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.GalleryElement>>("workGallery");

		///<summary>
		/// Work Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("workHeader")]
		public virtual string WorkHeader => this.Value<string>("workHeader");

		///<summary>
		/// Menu ID
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("workMenuId")]
		public virtual string WorkMenuId => this.Value<string>("workMenuId");

		///<summary>
		/// Menu Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("workMenuName")]
		public virtual string WorkMenuName => this.Value<string>("workMenuName");

		///<summary>
		/// Work Sub Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.1")]
		[ImplementPropertyType("workSubHeader")]
		public virtual string WorkSubHeader => this.Value<string>("workSubHeader");
	}
}
